const STOCK_SYMBOLS = [
    { symbol: 'AAPL',  name: 'Apple Inc.' },
    { symbol: 'MSFT',  name: 'Microsoft Corporation' },
    { symbol: 'GOOGL', name: 'Alphabet Inc. Class A' },
    { symbol: 'GOOG',  name: 'Alphabet Inc. Class C' },
    { symbol: 'AMZN',  name: 'Amazon.com Inc.' },
    { symbol: 'NVDA',  name: 'NVIDIA Corporation' },
    { symbol: 'META',  name: 'Meta Platforms Inc.' },
    { symbol: 'TSLA',  name: 'Tesla Inc.' },
    { symbol: 'BRK.B', name: 'Berkshire Hathaway Inc.' },
    { symbol: 'UNH',   name: 'UnitedHealth Group Inc.' },
    { symbol: 'LLY',   name: 'Eli Lilly and Company' },
    { symbol: 'JPM',   name: 'JPMorgan Chase & Co.' },
    { symbol: 'XOM',   name: 'Exxon Mobil Corporation' },
    { symbol: 'V',     name: 'Visa Inc.' },
    { symbol: 'AVGO',  name: 'Broadcom Inc.' },
    { symbol: 'PG',    name: 'Procter & Gamble Co.' },
    { symbol: 'MA',    name: 'Mastercard Inc.' },
    { symbol: 'COST',  name: 'Costco Wholesale Corporation' },
    { symbol: 'HD',    name: 'The Home Depot Inc.' },
    { symbol: 'ABBV',  name: 'AbbVie Inc.' },
    { symbol: 'JNJ',   name: 'Johnson & Johnson' },
    { symbol: 'WMT',   name: 'Walmart Inc.' },
    { symbol: 'BAC',   name: 'Bank of America Corp.' },
    { symbol: 'NFLX',  name: 'Netflix Inc.' },
    { symbol: 'MRK',   name: 'Merck & Co. Inc.' },
    { symbol: 'CRM',   name: 'Salesforce Inc.' },
    { symbol: 'AMD',   name: 'Advanced Micro Devices Inc.' },
    { symbol: 'ORCL',  name: 'Oracle Corporation' },
    { symbol: 'ACN',   name: 'Accenture plc' },
    { symbol: 'KO',    name: 'The Coca-Cola Company' },
    { symbol: 'CSCO',  name: 'Cisco Systems Inc.' },
    { symbol: 'PEP',   name: 'PepsiCo Inc.' },
    { symbol: 'INTC',  name: 'Intel Corporation' },
    { symbol: 'IBM',   name: 'International Business Machines' },
    { symbol: 'GE',    name: 'GE Aerospace' },
    { symbol: 'TXN',   name: 'Texas Instruments Inc.' },
    { symbol: 'QCOM',  name: 'Qualcomm Inc.' },
    { symbol: 'INTU',  name: 'Intuit Inc.' },
    { symbol: 'NOW',   name: 'ServiceNow Inc.' },
    { symbol: 'RTX',   name: 'RTX Corporation' },
    { symbol: 'ADBE',  name: 'Adobe Inc.' },
    { symbol: 'AMAT',  name: 'Applied Materials Inc.' },
    { symbol: 'T',     name: 'AT&T Inc.' },
    { symbol: 'VZ',    name: 'Verizon Communications Inc.' },
    { symbol: 'CVX',   name: 'Chevron Corporation' },
    { symbol: 'NEE',   name: 'NextEra Energy Inc.' },
    { symbol: 'MU',    name: 'Micron Technology Inc.' },
    { symbol: 'SBUX',  name: 'Starbucks Corporation' },
    { symbol: 'LOW',   name: "Lowe's Companies Inc." },
    { symbol: 'ISRG',  name: 'Intuitive Surgical Inc.' },
    { symbol: 'MDT',   name: 'Medtronic plc' },
    { symbol: 'HON',   name: 'Honeywell International Inc.' },
    { symbol: 'BKNG',  name: 'Booking Holdings Inc.' },
    { symbol: 'PM',    name: 'Philip Morris International Inc.' },
    { symbol: 'TJX',   name: 'The TJX Companies Inc.' },
    { symbol: 'GS',    name: 'Goldman Sachs Group Inc.' },
    { symbol: 'UNP',   name: 'Union Pacific Corporation' },
    { symbol: 'BLK',   name: 'BlackRock Inc.' },
    { symbol: 'COP',   name: 'ConocoPhillips' },
    { symbol: 'SYK',   name: 'Stryker Corporation' },
    { symbol: 'AXP',   name: 'American Express Company' },
    { symbol: 'REGN',  name: 'Regeneron Pharmaceuticals Inc.' },
    { symbol: 'DE',    name: 'Deere & Company' },
    { symbol: 'MS',    name: 'Morgan Stanley' },
    { symbol: 'GILD',  name: 'Gilead Sciences Inc.' },
    { symbol: 'C',     name: 'Citigroup Inc.' },
    { symbol: 'KLAC',  name: 'KLA Corporation' },
    { symbol: 'LRCX',  name: 'Lam Research Corporation' },
    { symbol: 'BSX',   name: 'Boston Scientific Corporation' },
    { symbol: 'PANW',  name: 'Palo Alto Networks Inc.' },
    { symbol: 'WFC',   name: 'Wells Fargo & Company' },
    { symbol: 'DUK',   name: 'Duke Energy Corporation' },
    { symbol: 'USB',   name: 'U.S. Bancorp' },
    { symbol: 'PGR',   name: 'Progressive Corporation' },
    { symbol: 'AMGN',  name: 'Amgen Inc.' },
    { symbol: 'BMY',   name: 'Bristol-Myers Squibb Company' },
    { symbol: 'TGT',   name: 'Target Corporation' },
    { symbol: 'SO',    name: 'The Southern Company' },
    { symbol: 'ETN',   name: 'Eaton Corporation plc' },
    { symbol: 'SHW',   name: 'The Sherwin-Williams Company' },
    { symbol: 'ZTS',   name: 'Zoetis Inc.' },
    { symbol: 'SCHW',  name: 'Charles Schwab Corporation' },
    { symbol: 'CME',   name: 'CME Group Inc.' },
    { symbol: 'UBER',  name: 'Uber Technologies Inc.' },
    { symbol: 'PYPL',  name: 'PayPal Holdings Inc.' },
    { symbol: 'SHOP',  name: 'Shopify Inc.' },
    { symbol: 'SNAP',  name: 'Snap Inc.' },
    { symbol: 'COIN',  name: 'Coinbase Global Inc.' },
    { symbol: 'PLTR',  name: 'Palantir Technologies Inc.' },
    { symbol: 'ABNB',  name: 'Airbnb Inc.' },
    { symbol: 'CRWD',  name: 'CrowdStrike Holdings Inc.' },
    { symbol: 'DDOG',  name: 'Datadog Inc.' },
    { symbol: 'NET',   name: 'Cloudflare Inc.' },
    { symbol: 'SNOW',  name: 'Snowflake Inc.' },
    { symbol: 'TTD',   name: 'The Trade Desk Inc.' },
    { symbol: 'ROKU',  name: 'Roku Inc.' },
    { symbol: 'RIVN',  name: 'Rivian Automotive Inc.' },
    { symbol: 'NIO',   name: 'NIO Inc.' },
    { symbol: 'BABA',  name: 'Alibaba Group Holding Ltd.' },
    { symbol: 'TSM',   name: 'Taiwan Semiconductor Mfg. Co.' },
    { symbol: 'ASML',  name: 'ASML Holding N.V.' },
    { symbol: 'SAP',   name: 'SAP SE' },
    { symbol: 'F',     name: 'Ford Motor Company' },
    { symbol: 'GM',    name: 'General Motors Company' },
    { symbol: 'BA',    name: 'The Boeing Company' },
    { symbol: 'LMT',   name: 'Lockheed Martin Corporation' },
    { symbol: 'CAT',   name: 'Caterpillar Inc.' },
    { symbol: 'MMM',   name: '3M Company' },
    { symbol: 'DHR',   name: 'Danaher Corporation' },
    { symbol: 'FDX',   name: 'FedEx Corporation' },
    { symbol: 'UPS',   name: 'United Parcel Service Inc.' },
    { symbol: 'NKE',   name: 'Nike Inc.' },
    { symbol: 'DIS',   name: 'The Walt Disney Company' },
    { symbol: 'CMCSA', name: 'Comcast Corporation' },
    { symbol: 'EA',    name: 'Electronic Arts Inc.' },
    { symbol: 'SPY',   name: 'SPDR S&P 500 ETF Trust' },
    { symbol: 'QQQ',   name: 'Invesco QQQ Trust' },
    { symbol: 'IWM',   name: 'iShares Russell 2000 ETF' },
    { symbol: 'GLD',   name: 'SPDR Gold Shares' },
    { symbol: 'VTI',   name: 'Vanguard Total Stock Market ETF' },
    { symbol: 'VOO',   name: 'Vanguard S&P 500 ETF' },
    { symbol: 'ARKK',  name: 'ARK Innovation ETF' },
    { symbol: 'XLK',   name: 'Technology Select Sector SPDR' },
    { symbol: 'XLF',   name: 'Financial Select Sector SPDR' },
    { symbol: 'XLE',   name: 'Energy Select Sector SPDR' },
];
